# Generated by Django 4.0.4 on 2022-07-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employer'),
        ),
        migrations.AddField(
            model_name='office',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.company'),
        ),
        migrations.AddField(
            model_name='office',
            name='workers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employers.employer'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employer'),
        ),
        migrations.AddField(
            model_name='checkedin',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.office'),
        ),
        migrations.AddField(
            model_name='checkedin',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
    ]
