# Generated by Django 4.0.4 on 2022-07-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_host',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(default='WdwBBDFj7fDR1ttcjRDq096Dqo1NB269', max_length=255),
        ),
    ]
