# Generated by Django 4.0.4 on 2022-07-17 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_is_host_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_status',
            field=models.CharField(default='completed', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(default='y712LjLhvqk9AedqGQrwIiiFVfdBqEXb', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='writer', max_length=255),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
