# Generated by Django 4.0.6 on 2022-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_role_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(default='wuawOW1Zlsi2rx1g2I6nqzTupVOo7zTP', max_length=255),
        ),
    ]
