# Generated by Django 4.0.6 on 2022-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_activationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(default='CBKw1I2FxEZ8Zz70TyCAdWOxXQTSTo3J', max_length=255),
        ),
    ]
