# Generated by Django 4.0.6 on 2022-07-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_activationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(default='kYyh9uktp9ziNXgoQr9tBlfOiqzeKUeJ', max_length=255),
        ),
    ]
