# Generated by Django 4.0.6 on 2022-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_activationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activationtoken',
            field=models.CharField(default='JwqZiApwN8Z3GfjwcS6Chw1iuqxEUzvf', max_length=255),
        ),
    ]
